<?php 
    get_header();
    require_once('includes/hero.php');
    require_once('includes/sec1.php');
    require_once('includes/sec2.php');
    require_once('includes/sec3.php');
    require_once('includes/sec4.php');
    require_once('includes/sec5.php');
    require_once('includes/sec6.php');
    require_once('includes/sec7.php');
    require_once('includes/sec8.php');
    get_footer();